version: '3.9'

services:
  backend:
    build:
      context: ./inzira_ticket_system_backend
      dockerfile: Dockerfile
    container_name: inzira-backend
    environment:
      # Common
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      app.cors.allowed-origins: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173}
      # Database (override via compose profiles)
      DB_URL: ${DB_URL:-jdbc:h2:file:./data/inzira;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
      DB_USERNAME: ${DB_USERNAME:-sa}
      DB_PASSWORD: ${DB_PASSWORD:-}
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - postgres
    profiles: [postgres]

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: inzira
      POSTGRES_USER: inzira
      POSTGRES_PASSWORD: inzira
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: [postgres]

  backend-mysql:
    build:
      context: ./inzira_ticket_system_backend
      dockerfile: Dockerfile
    container_name: inzira-backend-mysql
    environment:
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      app.cors.allowed-origins: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173}
      DB_URL: jdbc:mysql://mysql:3306/inzira
      DB_USERNAME: inzira
      DB_PASSWORD: inzira
    ports:
      - "8081:8080"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - mysql
    profiles: [mysql]

  mysql:
    image: mysql:8.4
    command: ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inzira
      MYSQL_USER: inzira
      MYSQL_PASSWORD: inzira
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    profiles: [mysql]

volumes:
  pgdata:
  mysqldata:
  backend_uploads:
